# Generated by Django 5.0.6 on 2024-06-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
