# Generated by Django 5.0.6 on 2024-06-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addproduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='product_id',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
