# Generated by Django 5.0.6 on 2024-06-04 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addcategory', '0001_initial'),
        ('Addproduct', '0002_alter_addproduct_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Addcategory.addcategory'),
        ),
    ]
