# Generated by Django 5.0.6 on 2024-06-05 05:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addproduct', '0003_alter_addproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
