# Generated by Django 5.0.6 on 2024-06-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addorder', '0002_addorder_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addorder',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
