# Generated by Django 5.0.6 on 2024-06-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addorder', '0003_alter_addorder_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addorder',
            name='expiry_date',
        ),
    ]
