# Generated by Django 5.0.6 on 2024-06-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addorder', '0005_addorder_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addorder',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
