# Generated by Django 5.0.6 on 2024-06-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addorder', '0006_addorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addorder',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
