# Generated by Django 5.0.6 on 2024-06-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addorder', '0007_alter_addorder_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addorder',
            name='expiry_date',
        ),
    ]
