# Generated by Django 5.0.6 on 2024-06-06 00:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addorder', '0008_remove_addorder_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
